### ISSUE TITLE
Set up utilities

### ISSUE THREAD

**Issue by DamitryDong** [nss-evening-cohort-29/hhpwup2u#4]
User Story
-ClearDom
-renderToDom
-StartApp

Acceptance Criteria
Just to at lease have those 3 utility functions.

Dependecies
Modularize

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Created a new file utils/domFunctions.js with clearDom, renderToDom, and startApp functions. Updated main.js to use these new functions and removed old code.

You can review changes in this commit: https://github.com/mnmnk43434/nss-evening-cohort-29-hhpwup2u-9/commit/a9eeeee5e7949be3798505494424011635df32f8.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
