### ISSUE TITLE
Dom Build

### ISSUE THREAD

**Issue by DamitryDong** [nss-evening-cohort-29/hhpwup2u#5]
User Story
Only focus on building the physical HTML, no functionality require yet. 

Acceptance Criteria
Have all physical criteria needed for MVP without functionality. 

Dependecies
Modularize

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Updated the index.html file to include the basic structure for the MVP. Added placeholder sections for the header, main content, and footer. Also updated the main.js file to remove the initial content and prepare for modular structure.

You can review changes in this commit: https://github.com/mnmnk43434/nss-evening-cohort-29-hhpwup2u-9/commit/08140c8ff121721e3952b9beb3360ffee510c38c.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
