### ISSUE TITLE
Form Build

### ISSUE THREAD

**Issue by DamitryDong** [nss-evening-cohort-29/hhpwup2u#7]
User Story
Build the form (Dont style, just paste a form from Bootstrap)

Acceptance Criteria
just physical form.

Dependecies
Modularize

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Create a new form component using Bootstrap and update main.js to include it. This satisfies the user story to build a form without styling, using Bootstrap.

You can review changes in this commit: https://github.com/mnmnk43434/nss-evening-cohort-29-hhpwup2u-9/commit/e507309b000870f1853679a6980fc069aa2ee58f.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
