### ISSUE TITLE
Nav Build

### ISSUE THREAD

**Issue by DamitryDong** [nss-evening-cohort-29/hhpwup2u#9]
User Story
Just build the Nav bar.

Acceptance Criteria
No functionality is needed just physical.

Dependecies
modularize.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Created a basic navigation bar in the index.html file and added corresponding styles in the main.scss file. The navigation bar is purely structural without functionality, as per the requirements.

You can review changes in this commit: https://github.com/mnmnk43434/nss-evening-cohort-29-hhpwup2u-9/commit/da6537215cfa6b55363432a510c4ad85d2163c87.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
